spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/event_scope_db
    username: postgres
    password: postgres

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

